name: example
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:      # 수동 실행을 위해 추가 가능
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 213100
          schedule-id: 100002
          seat-id: 0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '티켓사세요 http://ticket.melon.com/performance/index.htm?prodId=213100'
